config/routes.rb
Twitter::Application.routes.draw do
  get "tweets/new"
  get "tweets/show"
  get "tweets/list"
  delete "tweets/delete"
  post "tweets/create"

  devise_for :users

  get "pages/index"
  get "pages/about"
  get "pages/contact"
  get "pages/careers"

  match "/careers" => "pages#careers"
  match "/about" => "pages#about"
  match "/contact" => "pages#contact"

  root :to => 'pages#index'
end

app/models/tweet.rb
# ================================================
# MODEL ==========================================
# ================================================
class Tweet < ActiveRecord::Base
  belongs_to :user
  attr_accessible :message

  validates :user, presence: true

  # Static Method:
  #   Tweet.search_via_message
  def self.search_via_message(message)
    Tweet.where(:message => message)
  end
  
  # Normal Method:
  #   tweet = ....
  #   tweet.convert_to_whatever
  def convert_to_whatever()
    self.message = "Whatever"
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
    @phone_number = "555-555-5555"
    @foo = ["foo", "bar", "baz"]
  end

  def careers
  end
end

app/controllers/tweets_controller.rb
# ================================================
# CONTROLLER =====================================
# ================================================
class TweetsController < ApplicationController
  def new
  end

  def create
    redirect_to root_path unless user_signed_in?

    @tweet = Tweet.new(params[:tweet])

    @tweet.user = current_user
    @tweet.save

    redirect_to tweets_list_path
  end

  def show
  end

  def list
    @tweets = Tweet.all
  end

  def delete
    @tweet = Tweet.find(params[:format].to_i)
    @tweet.destroy

    redirect_to tweets_list_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <h1>Twitter</h1>

    <% if user_signed_in? %>
      <%= link_to tweets_new_path do %>
        <button>Compose Tweet</button>
        <br/>
        <br/>
      <% end %>
    <% end %>

    <% [["About", about_path], ["Careers", careers_path], ["Contact Us", contact_path]].each do |definition| %>
      <%= link_to definition[0], definition[1] %>

      &nbsp;
      &nbsp;
      &nbsp;

    <% end %>

    <!-- User Controls -->
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>

    <hr/>

    <!-- Injects here from your view -->
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
About us

app/views/pages/careers.html.erb
careers

app/views/pages/contact.html.erb
Contact us
<br/>
Call us at <%= @phone_number %>

<hr/>

<% @foo.each do |element| %>
  <%= element %>
  <br/>
<% end %>

<hr/>

The var is <%= params[:var] %>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/list.html.erb
<%
# ================================================
# VIEW ===========================================
# ================================================
%>

<% @tweets.each do |tweet| %>
  <b><%= tweet.user.email %></b>
  <br/>
  <%= tweet.created_at %>
  <br/>
  <%= tweet.message %>
  <br/>
  <%= link_to "Delete", tweets_delete_path(tweet), :method => :delete %>
  <hr/>
<% end %>

app/views/tweets/new.html.erb
<% if user_signed_in? %>
  <%= form_for :tweet, :url => tweets_create_path, :method => :post do |f| %>
    <%= f.text_area :message %>
    <br/>
    <%= f.submit "Post Tweet" %>
  <% end %>
<% else %>
  Please sign in.
<% end %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>